# The scraper uses host networking to reach the hotspot on the LAN
# (192.168.1.1). Prometheus, dashboard, and optional Grafana share a
# bridge network and expose ports to 0.0.0.0 so other devices on the LAN can connect.
#
# Ports used: scraper :9100, prometheus :9090, dashboard :8080, grafana(optional) :3000

services:
  scraper:
    build:
      context: ./scraper
      dockerfile: Containerfile
    container_name: hotspot-scraper
    network_mode: host
    environment:
      - HOTSPOT_URL=${HOTSPOT_URL:-http://192.168.1.1}
      - HOTSPOT_USERNAME=${HOTSPOT_USERNAME:-admin}
      - HOTSPOT_PASSWORD=${HOTSPOT_PASSWORD}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL:-10}
      - DASHBOARD_HISTORY_SECONDS=${DASHBOARD_HISTORY_SECONDS:-120}
      - PROCESS_HEARTBEAT_INTERVAL=${PROCESS_HEARTBEAT_INTERVAL:-1}
      - METRICS_PORT=9100
      - SSE_PORT=9101
      - HISTORY_RETENTION_SECONDS=${HISTORY_RETENTION_SECONDS:-3600}
      - HISTORY_MAX_POINTS=${HISTORY_MAX_POINTS:-5000}
    restart: unless-stopped

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: hotspot-prometheus
    profiles:
      - observability
      - grafana
    networks:
      - metrics
    ports:
      - "0.0.0.0:9090:9090"
    extra_hosts:
      - "host.containers.internal:host-gateway"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - scraper
    restart: unless-stopped

  # Optional full dashboard (disabled by default; enable with --profile grafana)
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: hotspot-grafana
    profiles:
      - grafana
    networks:
      - metrics
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/hotspot.json
    depends_on:
      - prometheus
    restart: unless-stopped

  dashboard:
    image: docker.io/library/nginx:alpine
    container_name: hotspot-dashboard
    networks:
      - metrics
    ports:
      - "0.0.0.0:8080:8080"
    extra_hosts:
      - "host.containers.internal:host-gateway"
    volumes:
      - ./dashboard/index.html:/usr/share/nginx/html/index.html:ro
      - ./dashboard/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  tunnel:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: hotspot-tunnel
    networks:
      - metrics
    command: ${TUNNEL_CMD:-tunnel --no-autoupdate --url http://dashboard:8080}
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN:-}
    depends_on:
      - dashboard
    restart: unless-stopped

networks:
  metrics:

volumes:
  prometheus_data:
  grafana_data:
