# All services use host networking so the scraper can reach the hotspot
# on the LAN (192.168.1.1) and Prometheus/Grafana can reach each other
# via localhost.
#
# Ports used: scraper :9100, prometheus :9090, grafana :3000

services:
  scraper:
    build:
      context: ./scraper
      dockerfile: Containerfile
    container_name: hotspot-scraper
    network_mode: host
    environment:
      - HOTSPOT_URL=${HOTSPOT_URL:-http://192.168.1.1}
      - HOTSPOT_USERNAME=${HOTSPOT_USERNAME:-admin}
      - HOTSPOT_PASSWORD=${HOTSPOT_PASSWORD}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL:-15}
      - METRICS_PORT=9100
    restart: unless-stopped

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: hotspot-prometheus
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - scraper
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: hotspot-grafana
    network_mode: host
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
